#!/bin/bash:w
# Docker 서비스 파일 경로
DOCKER_SERVICE_FILE="/lib/systemd/system/docker.service"

# ExecStart 라인에서 '-H fd://' 부분이 있는지 확인
if grep -q 'ExecStart=/usr/bin/dockerd -H fd://' $DOCKER_SERVICE_FILE; then
    
    echo '/lib/systemd/system/docker.service 수정'

    # '-H fd://' 부분이 있는 경우, 해당 부분을 제거하기 위한 sed 명령어 실행
    echo "'"'-H fd://'"'"'부분이 있는 경우, 해당 부분을 제거하기 위한 sed 명령어 실행'
    echo 'sudo sed -i 's/ExecStart=\/usr\/bin\/dockerd -H fd:\/\/ /ExecStart=\/usr\/bin\/dockerd /' $DOCKER_SERVICE_FILE' 
    sudo sed -i 's/ExecStart=\/usr\/bin\/dockerd -H fd:\/\/ /ExecStart=\/usr\/bin\/dockerd /' $DOCKER_SERVICE_FILE

    # systemd 데몬을 리로드하여 변경 사항 적용
    echo 'systemd 데몬을 리로드하여 변경 사항 적용'
    echo 'sudo systemctl daemon-reload'
    sudo systemctl daemon-reload

    # Docker 서비스 재시작
    echo 'Docker 서비스 재시작'
    echo 'sudo systemctl restart docker.service'
    sudo systemctl restart docker.service
else
    # '-H fd://' 부분이 없는 경우, 메시지 출력 후 스크립트 종료
    echo "No changes were made as the specified line does not exist in the Docker service file."
fi

